SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Solo Leveling"

# Игрок
PLAYER_SPEED = 5
PLAYER_DAMAGE = 2
PLAYER_MAX_HP = 100
PLAYER_HP = 100

# Гоблин
GOBLIN_SPEED = 2
GOBLIN_DAMAGE = 0.3
GOBLIN_HP = 80
GOBLIN_MAX_HP = 80
GOBLIN_ATTACK_RADIUS = 35

# Слизень
MUCUS_MAX_HP = 50
MUCUS_HP = 50
MUCUS_DAMAGE = 0.2
MUCUS_SPEED = 2
MUCUS_ATTACK_RADIUS = 45

# Радиусы
RADIUS = 300
AGGRO_RADIUS_MUCUS = 300

# Настройки игры
TILE_SCALING = 1.0
CAMERA_LERP = 0.12

# Звуки
SOUND_MONSTER_SWORD = "monster_sword_strike.mp3"
SOUND_AIR_SWORD = "air_sword_strike.mp3"